- hosts: all
  become: yes

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install Docker SDK
      pip:
        name: docker

    - name: Run Nginx Container
      docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
